### PR TITLE
Checkpointing (quasi-Newton solver)

### LINKED ISSUE #686: Add advanced checkpoint/restart capabilities to Hiop
Many HPC applications need to implement a checkpoint/restart capability to address either:

- maximum job time allocations (e.g., no jobs can run for more than 24 hours)
- fault tolerance (e.g., individual parts of a supercomputer can fail leading to premature job failure)

To address these concerns, typical HPC applications periodically write their internal state to hard drive (checkpointing) and then have the ability to restart and resume progress from the last checkpoint file.

Hiop has some ability to warm start through the `get_starting_point()` or `get_warm_start()`. However, it would be better if Hiop could save more of its internal state to do a better restart.

The [::axom::sidre](https://axom.readthedocs.io/en/develop/axom/sidre/docs/sphinx/index.html) package provides a flexible checkpoint/restart API and implementation. Multiple LLNL packages use `::axom::sidre`. The repository is [here](https://github.com/LLNL/axom). It's buildable with Spack.

### PR DESCRIPTION
**Pull request by cnpetra**
Adds API for checkpointing and support for restart via user options.

closes #686 

- [x] display iteration number from before restart
- [x] provide example for the load/save API
- [x] update user manual
- [x] metadata

### CODE REVIEW

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 1]
```diff
@@ -67,11 +67,15 @@
 #include "hiopPDPerturbation.hpp"
 #include "hiopFactAcceptor.hpp"
 
+#ifdef HIOP_USE_AXOM
+#include <axom/sidre/core/DataStore.hpp>
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.hpp]:
```suggestion
namespace axom {
namespace sidre {
class DataStore; // forward declaration
}
}
```
`hiopAlgFilterIPM.hpp` only needs a forward declaration, so it's better to avoid including `DataStore.hpp` in a client-facing header file.

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 2]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
   virtual ~hiopAlgFilterIPMQuasiNewton();
 
   virtual hiopSolveStatus run();
+
+  // note that checkpointing is only available with a axom-enabled build
+#ifdef HIOP_USE_AXOM
+  /**
+   * @brief Save state of HiOp algorithm to a sidre data store.
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.hpp]:
```suggestion
   * @brief Save state of HiOp algorithm to a sidre data store for checkpoint/warmstart.
```

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 3]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+   * @param data_store a pointer to DataStore
+   *
+   * @details 
+   * A new sidre::group "hiop solver" is created within data_store. Then a sidre::View 
+   * is created within the group for each of the algorithm's states and the states are
+   * copied in the corresponding views. 
+   */
+  virtual void save_state_to_data_store(::axom::sidre::DataStore* data_store);
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.hpp]:
```suggestion
  virtual void save_state_to_data_store(::axom::sidre::DataStore &data_store);
```
I think a reference makes the meaning clearer here. `data_store` is not allowed to be a nullptr, and the client (caller) is *not* transferring ownership of the pointer to `save_state_to_data_store`.

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 4]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+
+  /**
+   * @brief Load state of HiOp algorithm from a sidre data store.
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.hpp]:
```suggestion
   * @brief Load state of HiOp algorithm from a sidre data store to prepare for a warm (re)start.
```

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 5]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+   * @param data_store a pointer to DataStore
+   *
+   * @details 
+   * Copies views from the data store sidre::group (named "hiop solver") to HiOp algorithm's
+   * state variables. The group should be created by first calling save_state_to_data_store 
+   * for a problem/NLP of the same sizes as the problem for which load_state_from_data_store
+   * is called. This ensures the views have the names and sizes expected by this method. 
+   * Otherwise a std::runtime_error exception is thrown.
+   */ 
+  virtual void load_state_from_data_store(const ::axom::sidre::DataStore* data_store);
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.hpp]:
```suggestion
  virtual void load_state_from_data_store(const ::axom::sidre::DataStore &data_store);
```
Again, I think reference makes the meaning clear and shows that `nullptr` isn't a valid incoming value. It avoids the uncertainty that comes with a raw pointer.

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 6]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+   * A new sidre::group "hiop solver" is created within data_store. Then a sidre::View 
+   * is created within the group for each of the algorithm's states and the states are
+   * copied in the corresponding views. 
+   */
+  virtual void save_state_to_data_store(::axom::sidre::DataStore* data_store);
+
+  /**
+   * @brief Load state of HiOp algorithm from a sidre data store.
+   * @param data_store a pointer to DataStore
+   *
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.hpp:385]:
```suggestion
   * @exception std::runtime indicates that the load failed or that the data in the file have incorrect names or sizes.
   *
```

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 7]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+    sidre::IOManager writer(this->get_nlp()->get_comm());
+    int n_files;
+    MPI_Comm_size(this->get_nlp()->get_comm(), &n_files);
+    writer.write(ds->getRoot(), n_files, path.c_str(), sidre::Group::getDefaultIOProtocol());
+  } catch(const std::exception& exp) {
+    nlp->log->printf(hovError, "Error in saving checkpoint to file '%s'\n", path.c_str());
+    nlp->log->printf(hovError,  "  Addtl info: %s\n", exp.what());
+    success = false;    
+  }  
+  delete ds;
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp]:
```suggestion
  sidre::DataStore ds;
  try {
    this->save_state_to_data_store(ds);

    sidre::IOManager writer(this->get_nlp()->get_comm());
    int n_files;
    MPI_Comm_size(this->get_nlp()->get_comm(), &n_files);
    writer.write(ds->getRoot(), n_files, path.c_str(), sidre::Group::getDefaultIOProtocol());
  } catch(const std::exception& exp) {
    nlp->log->printf(hovError, "Error in saving checkpoint to file '%s'\n", path.c_str());
    nlp->log->printf(hovError,  "  Addtl info: %s\n", exp.what());
    success = false;    
  }  
```
There is no need to use dynamic memory here.

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 8]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  return success;
+}
+
+bool hiopAlgFilterIPMQuasiNewton::load_state_from_file(const ::std::string& path) noexcept
+{
+  sidre::DataStore* ds = nullptr;
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp]:
```suggestion
  sidre::DataStore ds;
```

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 9]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  auto success = true;
+  try {
+    ds = new sidre::DataStore();
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp]:
```suggestion
```

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 10]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+    reader.read(ds->getRoot(), path, false);
+    
+    this->load_state_from_data_store(ds);
+    
+  } catch(const std::exception& exp) {
+    nlp->log->printf(hovError, "Error in loading checkpoint from file '%s'\n", path.c_str());
+    nlp->log->printf(hovError,  "  Addtl info: %s\n", exp.what());
+    success = false;
+  }
+  delete ds;
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp]:
```suggestion
```

**Review by tepperly — COMMENTED** [review]
I'll check more later.

File: src/Optimization/hiopAlgFilterIPM.hpp (hunk 3 above)
Comment (cnpetra) [reply src/Optimization/hiopAlgFilterIPM.hpp]: 100% agree, will use refs.

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 11]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+    assert(false && "const cast failed for Sidre::View");
+  }
+}
+
+void hiopAlgFilterIPMQuasiNewton::save_state_to_data_store(::axom::sidre::DataStore* ds)
+{
+  using IndType = sidre::IndexType;
+  sidre::Group* nlp_group = ds->getRoot()->createGroup("hiop solver");
+  
+  //create views for each member that needs to be saved
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp:1597]: It might be useful to include a little metadata too such as:
- the version of HiOp that's writing the file
- the iteration number?

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 12]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  copy_vec_to_new_view("zl", it_curr->get_zl(), nlp_group);
+  copy_vec_to_new_view("zu", it_curr->get_zu(), nlp_group);
+  copy_vec_to_new_view("vl", it_curr->get_vl(), nlp_group);
+  copy_vec_to_new_view("vu", it_curr->get_vu(), nlp_group);
+
+  //quasi-Newton Hessian approximation 
+  
+  //algorithmic parameters for this state
+  //mu, iteration number
+  const double alg_params[] = {_mu};
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp]: `alg_params` is defined but doesn't appear to be used.

File: src/Utils/hiopOptions.cpp [hunk 13]
```diff
@@ -1289,8 +1289,26 @@ void hiopOptionsNLP::register_options()
...
+  {
+    vector<string> range = {"yes", "no"};
+    constexpr char msgcs[] = "Save state of NLP solver to file specified by 'checkpoint_file'.";
+    register_str_option("checkpoint_save", range[1], range, msgcs);
+    
+    constexpr char msgcsN[] = "Iteration frequency of saving checkpoints to disk.";
+    register_int_option("checkpoint_save_every_N_iter", 10, 1, 1e+6, msgcsN);
 
+    constexpr char msgcf[] = "Path to checkpoint file. If present character '#' will be replaced "
+      "with the iteration number.";
```
Comment (tepperly) [inline src/Utils/hiopOptions.cpp]: The implementation only replaces the first occurrence of '#'.

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 14]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+void hiopAlgFilterIPMQuasiNewton::checkpointing_stuff()
+{
+  if(nlp->options->GetString("checkpoint_save")=="no") {
+    return;
+  }
+  int chk_every_N = nlp->options->GetInteger("checkpoint_save_every_N_iter");
+  //check iteration
+  if(iter_num>0 && iter_num % chk_every_N==0) {
+    using ::std::string;
+    // replace "#" in checkpointing file with iteration number
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp:1773]: Should it replace all occurrences of  '#' or just the first one?

**Review by tepperly — COMMENTED** [review]
I think this is all my feedback.

**Comment by tepperly** [comment]
I thought about it some more over lunch, and I think `load_state_from_data_store()` and `save_state_to_data_store()` should take a `::axom::sidre::Group &` as it's argument rather than a `::axom::sidre::DataStore &`. The `Group` argument should specify the group where the save/load should take place from rather than it being a fixed location relative to the root `DataStore`. 

You can get the `DataStore` from the `Group` in case there is a need for that.

IMHO, this is an improvement because if HiOp is part of a complex program, the outer program may want to encapsulate the HiOp part of the checkpoint in some group that's potentially several levels down from the DataStore root group. It also leaves the door open for their to be multiple instances of HiOp active in the running program that all need to be checkpointed.  The current design can only support checkpointing of one HiOp instance in a given DataStore.

File: src/Optimization/hiopAlgFilterIPM.cpp (hunk 12 above)
Comment (cnpetra) [reply src/Optimization/hiopAlgFilterIPM.cpp]: will do, I am only half way through here.

**Comment by cnpetra** [comment]
> I thought about it some more over lunch, and I think `load_state_from_data_store()` and `save_state_to_data_store()` should take a `::axom::sidre::Group &` as it's argument rather than a `::axom::sidre::DataStore &`. The `Group` argument should specify the group where the save/load should take place from rather than it being a fixed location relative to the root `DataStore`.
> 
> You can get the `DataStore` from the `Group` in case there is a need for that.
> 
> IMHO, this is an improvement because if HiOp is part of a complex program, the outer program may want to encapsulate the HiOp part of the checkpoint in some group that's potentially several levels down from the DataStore root group. It also leaves the door open for their to be multiple instances of HiOp active in the running program that all need to be checkpointed. The current design can only support checkpointing of one HiOp instance in a given DataStore.

I take it that `load_state_from_data_store()` and `save_state_to_data_store()` "APIs" would do the job on your end. I see the flexibility of working with the `sidre::group` and will make the change. Will have you as a reviewer to have a final look when the PR ready.

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 15]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  delete ds;
+  return success;
+}
+
+void hiopAlgFilterIPMQuasiNewton::
+copy_vec_to_new_view(const ::std::string& name, const hiopVector* vec, sidre::Group* nlp_group)
+{
+  using IndType = sidre::IndexType;
+  const IndType size = vec->get_local_size();
+  sidre::View* dest = nlp_group->createViewAndAllocate(name, sidre::DOUBLE_ID, size);
```
Comment (tepperly) [inline src/Optimization/hiopAlgFilterIPM.cpp]: In LiDO, we often use the same DataStore for the whole run. If we were to call this multiple times, I think it will fail because the views would already exist.
Right now this method always makes a new view. It would be better if it checked first if the view already exists. If it already exists in the Group, use that one. If it doesn't already exist, create a new view.

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 16]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+   * state variables. The group should be created by first calling save_state_to_data_store 
+   * for a problem/NLP of the same sizes as the problem for which load_state_from_data_store
+   * is called. This ensures the views have the names and sizes expected by this method. 
+   * Otherwise a std::runtime_error exception is thrown.
+   */ 
+  virtual void load_state_from_data_store(const ::axom::sidre::DataStore* data_store);
+
+  /**
+   * @brief Save the state of the algorithm to the file
+   * @param path   the name of the file
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.hpp]: Indentation

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 17]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+   * 
+   * @details
+   * Internally, HiOp uses axom::sidre::DataStore and sidre's scalable IO. A detailed
+   * error description is sent to the log if an error or exception is caught.
+   */
+  bool save_state_to_file(const ::std::string& path) noexcept;
+
+  /**
+   * @brief load the state of the algorithm from file
+   * @param path   the name of the file to load from
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.hpp]: Indentation

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 18]
```diff
@@ -339,8 +345,74 @@ class hiopAlgFilterIPMQuasiNewton : public hiopAlgFilterIPMBase
...
+   * @return true if successful, false otherwise
+   * 
+   * @details
+   * Internally, HiOp uses axom::sidre::DataStore and sidre's scalable IO. A detailed
+   * error description is sent to the log if an error or exception is caught.
+   */
+  bool save_state_to_file(const ::std::string& path) noexcept;
+
+  /**
+   * @brief load the state of the algorithm from file
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.hpp]: from a file

File: src/Utils/hiopOptions.cpp [hunk 19]
```diff
@@ -1551,6 +1569,26 @@ void hiopOptionsNLP::ensure_consistence()
...
+                 "are ignored.\n");
+      //reset them to as not being user defined to avoid triggering the message. 
+      for(auto opt2 : chkpnt_opts) {
+        mOptions_[opt2]->specifiedInFile = false;
+        mOptions_[opt2]->specifiedAtRuntime = false;
+      }
+      break;
+    }
+  }
+#endif
```
Comment (nychiang) [inline src/Utils/hiopOptions.cpp:1590]: LGTM, but maybe we should test it first, i.e., build without axom and give checkpoint_file in the hiop.options.

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 20]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  copy_vec_from_view("yc", it_curr->get_yc(), nlp_group);
+  copy_vec_from_view("zl", it_curr->get_zl(), nlp_group);
+  copy_vec_from_view("zu", it_curr->get_zu(), nlp_group);
+  copy_vec_from_view("vl", it_curr->get_vl(), nlp_group);
+  copy_vec_from_view("vu", it_curr->get_vu(), nlp_group);
+
+
+}
+
+void hiopAlgFilterIPMQuasiNewton::checkpointing_stuff()
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.cpp:1764]: Style Guidelines.
There should be spaces before and after each operator, e.g. line 1675, 1655,...

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 21]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  copy_vec_from_view("sxl", it_curr->get_sxl(), nlp_group);
+  copy_vec_from_view("sxu", it_curr->get_sxu(), nlp_group);
+  copy_vec_from_view("sdl", it_curr->get_sdl(), nlp_group);
+  copy_vec_from_view("sdu", it_curr->get_sdu(), nlp_group);
+  copy_vec_from_view("yc", it_curr->get_yc(), nlp_group);
+  copy_vec_from_view("zl", it_curr->get_zl(), nlp_group);
+  copy_vec_from_view("zu", it_curr->get_zu(), nlp_group);
+  copy_vec_from_view("vl", it_curr->get_vl(), nlp_group);
+  copy_vec_from_view("vu", it_curr->get_vu(), nlp_group);
+
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.cpp:1705]: copy_vec_from_view("yd", it_curr->get_yd(), nlp_group);

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 22]
```diff
@@ -1485,6 +1529,170 @@ void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int u
...
+  copy_vec_to_new_view("sxl", it_curr->get_sxl(), nlp_group);
+  copy_vec_to_new_view("sxu", it_curr->get_sxu(), nlp_group);
+  copy_vec_to_new_view("sdl", it_curr->get_sdl(), nlp_group);
+  copy_vec_to_new_view("sdu", it_curr->get_sdu(), nlp_group);
+  copy_vec_to_new_view("yc", it_curr->get_yc(), nlp_group);
+  copy_vec_to_new_view("zl", it_curr->get_zl(), nlp_group);
+  copy_vec_to_new_view("zu", it_curr->get_zu(), nlp_group);
+  copy_vec_to_new_view("vl", it_curr->get_vl(), nlp_group);
+  copy_vec_to_new_view("vu", it_curr->get_vu(), nlp_group);
+
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.cpp]: copy_vec_to_new_view("yd", it_curr->get_yd(), nlp_group);

**Review by nychiang — COMMENTED** [review]
Add minor comments

File: src/Optimization/hiopAlgFilterIPM.cpp (hunk 20 above)
Comment (cnpetra) [reply src/Optimization/hiopAlgFilterIPM.cpp:1764]: > Style Guidelines. There should be spaces before and after each operator, e.g. line 1675, 1680,...

can you be more specific about the guideline?

File: src/Optimization/hiopAlgFilterIPM.cpp (hunk 15 above)
Comment (cnpetra) [reply src/Optimization/hiopAlgFilterIPM.cpp]: last commit does that. note that an exception will be thrown if the view exists and has a different number of elements than HiOp's state variable.

File: src/Optimization/hiopAlgFilterIPM.cpp (hunk 20 above)
Comment (nychiang) [reply src/Optimization/hiopAlgFilterIPM.cpp:1764]: I mean space before and after operator "==".

Comment (tepperly) [reply src/Optimization/hiopAlgFilterIPM.cpp:1764]: Our CMake build that uses [BLT](https://github.com/LLNL/blt) auto formats everything using clang-format (and a configuration file) with a `make style`.  Also `make check` verifies that the code matches the clang-format style configuration, so a PR can't be merged without complying with the style.

**Comment by tepperly** [comment]
> > I thought about it some more over lunch, and I think `load_state_from_data_store()` and `save_state_to_data_store()` should take a `::axom::sidre::Group &` as it's argument rather than a `::axom::sidre::DataStore &`. The `Group` argument should specify the group where the save/load should take place from rather than it being a fixed location relative to the root `DataStore`.
> > You can get the `DataStore` from the `Group` in case there is a need for that.
> > IMHO, this is an improvement because if HiOp is part of a complex program, the outer program may want to encapsulate the HiOp part of the checkpoint in some group that's potentially several levels down from the DataStore root group. It also leaves the door open for their to be multiple instances of HiOp active in the running program that all need to be checkpointed. The current design can only support checkpointing of one HiOp instance in a given DataStore.
> 
> I take it that `load_state_from_data_store()` and `save_state_to_data_store()` "APIs" would do the job on your end. I see the flexibility of working with the `sidre::group` and will make the change. Will have you as a reviewer to have a final look when the PR ready.

The load/save methods offer the most flexibility for LiDO and its clients. I haven't double checked that we have the right HiOp object handle to call them.

**Comment by cnpetra** [comment]
> > > I thought about it some more over lunch, and I think `load_state_from_data_store()` and `save_state_to_data_store()` should take a `::axom::sidre::Group &` as it's argument rather than a `::axom::sidre::DataStore &`. The `Group` argument should specify the group where the save/load should take place from rather than it being a fixed location relative to the root `DataStore`.
> > > You can get the `DataStore` from the `Group` in case there is a need for that.
> > > IMHO, this is an improvement because if HiOp is part of a complex program, the outer program may want to encapsulate the HiOp part of the checkpoint in some group that's potentially several levels down from the DataStore root group. It also leaves the door open for their to be multiple instances of HiOp active in the running program that all need to be checkpointed. The current design can only support checkpointing of one HiOp instance in a given DataStore.
> > 
> > 
> > I take it that `load_state_from_data_store()` and `save_state_to_data_store()` "APIs" would do the job on your end. I see the flexibility of working with the `sidre::group` and will make the change. Will have you as a reviewer to have a final look when the PR ready.
> 
> The load/save methods offer the most flexibility for LiDO and its clients. I haven't double checked that we have the right HiOp object handle to call them.

LiDO for sure instantiates the algorithm class somewhere in there. That "algorithm" object should be used. For example, attach it to the interface. Will provide an example in this PR.

**Comment by cnpetra** [comment]
@tepperly please take a look [here](https://github.com/LLNL/hiop/blob/b78547549bab638d4f69ba85aa0620a1f3f2594c/src/Drivers/Dense/NlpDenseConsEx1Driver.cpp#L182) and [here](https://github.com/LLNL/hiop/blob/b78547549bab638d4f69ba85aa0620a1f3f2594c/src/Drivers/Dense/NlpDenseConsEx1.cpp#L224) at the use of the load/save API

**Comment by tepperly** [comment]
I'll try to look at it early this week. It's PA season.

File: CMakeLists.txt [hunk 23]
```diff
@@ -289,6 +290,15 @@ if(HIOP_USE_RAJA)
...
 
+if(HIOP_USE_AXOM)
+  find_package(AXOM CONFIG
+    PATHS ${AXOM_DIR} ${AXOM_DIR}/lib/cmake/
+    REQUIRED)
+  target_link_libraries(hiop_tpl INTERFACE axom)
+  message(STATUS "Found AXOM pkg-config: ${AXOM_CONFIG}")
+endif()
+  
+
```
Comment (nychiang) [inline CMakeLists.txt]: "checkpointing is not available for non-MPI builds due to Axom having MPI
as a dependency"
Should we add `if(HIOP_USE_MPI)` after line 293, and set `HIOP_USE_AXOM` to `OFF` if MPI is not used?

File: src/Optimization/hiopKKTLinSys.cpp [hunk 24]
```diff
@@ -947,7 +947,7 @@ bool hiopKKTLinSys::compute_directions_w_IR(const hiopResidual* resid, hiopItera
   bool bret = bicgIR_->solve(dir, resid);
 
   nlp_->runStats.kkt.nIterRefinInner += bicgIR_->get_sol_num_iter();
-  nlp_->runStats.kkt.tmSolveInner.stop();
+  //nlp_->runStats.kkt.tmSolveInner.stop();
```
Comment (nychiang) [inline src/Optimization/hiopKKTLinSys.cpp]: Remove this line. (I have checked the code where kkt.tmSolveInner starts and stops.

File: src/Optimization/hiopAlgFilterIPM.hpp [hunk 25]
```diff
@@ -67,11 +67,19 @@
...
+}
+}
+#endif
+
 #include "hiopTimer.hpp"
 
 namespace hiop
 {
-
+
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.hpp]: Remove spaces

File: src/Optimization/hiopHessianLowRank.hpp [hunk 26]
```diff
@@ -124,6 +124,7 @@ class hiopHessianLowRank : public hiopMatrix
   virtual void timesVecCmn(double beta, hiopVector& y, double alpha, const hiopVector&x, bool addLogBarTerm = false) const;
 
 protected:
+  friend class hiopAlgFilterIPMQuasiNewton;  
   int l_max; //max memory size
   int l_curr; //number of pairs currently stored
```
Comment (nychiang) [inline src/Optimization/hiopHessianLowRank.hpp:129]: All member variable names should end with trailing underscore to distingusish them from local variables.
Well, seems we need to change many things here and there. Maybe a new PR?

File: src/Optimization/hiopHessianLowRank.cpp [hunk 27]
```diff
@@ -196,6 +199,24 @@ hiopHessianLowRank::~hiopHessianLowRank()
   }
 }
 
+void hiopHessianLowRank::alloc_for_limited_mem(const size_type& mem_length)
+{
+  //note: St_ and Yt_ always have l_curr rows
+  if(l_curr == mem_length) {
```
Comment (nychiang) [inline src/Optimization/hiopHessianLowRank.cpp:205]: l_curr is a member variable.
All member variable names should end with trailing underscore to distingusish them from local variables. 
Maybe we should address this in another PR.

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 28]
```diff
@@ -1457,12 +1520,12 @@ hiopSolveStatus hiopAlgFilterIPMQuasiNewton::run()
 
 void hiopAlgFilterIPMQuasiNewton::outputIteration(int lsStatus, int lsNum, int use_soc, int use_fr)
 {
-  if(iter_num/10*10==iter_num)
+  if(iter_num_/10*10==iter_num_)
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.cpp:1523]: should we use iter_num_total_ here?

File: src/Optimization/hiopAlgFilterIPM.cpp [hunk 29]
```diff
@@ -2476,12 +2782,12 @@ hiopSolveStatus hiopAlgFilterIPMNewton::run()
 
 void hiopAlgFilterIPMNewton::outputIteration(int lsStatus, int lsNum, int use_soc, int use_fr)
 {
-  if(iter_num/10*10==iter_num)
+  if(iter_num_/10*10==iter_num_)
```
Comment (nychiang) [inline src/Optimization/hiopAlgFilterIPM.cpp:2785]: iter_num_total_?

**Review by nychiang — APPROVED** [review]
some minor comments.

**Comment by tepperly** [comment]
> @tepperly please take a look [here](https://github.com/LLNL/hiop/blob/b78547549bab638d4f69ba85aa0620a1f3f2594c/src/Drivers/Dense/NlpDenseConsEx1Driver.cpp#L182) and [here](https://github.com/LLNL/hiop/blob/b78547549bab638d4f69ba85aa0620a1f3f2594c/src/Drivers/Dense/NlpDenseConsEx1.cpp#L224) at the use of the load/save API

I looked over it again, and it looks good to me.

File: src/Optimization/hiopHessianLowRank.hpp (hunk 26 above)
Comment (cnpetra) [reply src/Optimization/hiopHessianLowRank.hpp:129]: yes

File: src/Optimization/hiopAlgFilterIPM.cpp (hunk 28 above)
Comment (cnpetra) [reply src/Optimization/hiopAlgFilterIPM.cpp:1523]: no, it will re-print header every 10 iterations, when restarting this may not happen at multiples of 10.
